apiVersion: v1
kind: Secret
metadata:
  name: app-secret                                # Name of the Secret (referenced in deployment.yaml)
type: Opaque
data:
  API_KEY: bXlTdXBlclNlY3JldEtleQ==               # Base64 encoded API key of "mySuperSecretKey"
                                                  # echo -n 'yourkey' | base64 (to generate yours)
                                                  # echo 'bXlTdXBlclNlY3JldEtleQ==' | base64 --decode (to decode)
                                                  