apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  API_KEY: bXlTdXBlclNlY3JldEtleQ==   # base64 of "mySuperSecretKey"
                                      # (Tip: echo -n 'mySuperSecretKey' | base64 to generate yours)

