apiVersion: v1
kind: Service
metadata:
  name: express-service                           # Name of the Service
spec:
  type: NodePort                                  # Exposes the app to the outside world
  selector:
    app: express-app                              # Must match the Deployment's pod label
  ports:
    - protocol: TCP
      port: 3000                                  # Port *inside* the cluster (Service port)
      targetPort: 3000                            # Pod/container port (must match containerPort in deployment.yaml)
      nodePort: 30080                             # Port on the Minikube VM (or Node) accessible externally
